### ISSUE TITLE
v11.0 - Confirmar nomina de vacaciones

### ISSUE THREAD

**Issue by csotox** [KonosCL/addons-konos#10]
Cuando se trata de Confirmar la nomina de un empleado que va a ser enviado de vacaciones, muestra el siguiente mensaje: 

> Código python erróneo en la regla de salario BONO DE PRODUCCION (PROD).

No poseo mas información.

**Comment by dansanti** [comment]
Hola! debes poner datos de ejemplo para poder replicar el problema
