### ISSUE TITLE
Funcion _getNeto no declarada

### ISSUE THREAD

**Issue by celm1990** [KonosCL/addons-konos#19]
La funcion [_getNeto](https://github.com/KonosCL/addons-konos/blob/11.0/l10n_cl_chart_of_account/models/account_invoice.py#L36) no existe en el modulo del plan contable de chile, esta funcion se agrega en el modulo de Daniel, pero cuando instalas solo el plan contable sin ese modulo de Daniel, al crear una factura sale un error.
![image](https://user-images.githubusercontent.com/7775116/40332599-2bb76f4c-5d1a-11e8-876d-30ed5d4c4283.png)

Que tan factible es mover esta [funcion](https://github.com/dansanti/l10n_cl_fe/blob/11.0/models/invoice.py#L145-L159) del modulo [l10n_cl_fe](https://github.com/dansanti/l10n_cl_fe) al modulo del plan contable???

CC: @dansanti

**Comment by dansanti** [comment]
Hay que migrar lo, porque sn este módulo también se subirán los cambios
para las boletas de honorarios y la lógica de retención de impuesto que cree

**Comment by nelsonramirezs** [comment]
Migremos!

**Comment by nelsonramirezs** [comment]
último commit resuelve este issue
