### ISSUE TITLE
Metodo _check_and_recompute_days no existe en hr.holidays

### ISSUE THREAD

**Issue by celm1990** [KonosCL/addons-konos#28]
Al querer ingresar una ausencia se obtiene el siguiente error

![image](https://user-images.githubusercontent.com/7775116/44818906-23ffff80-abda-11e8-9478-10fed7c1221a.png)

Revisando el historial de cambios, en este commit e2c4e591a0ea919de1017429174d6ed0a7169cf4 comentastes esa parte del codigo, pero en este nuevo commit  https://github.com/KonosCL/addons-konos/commit/6c95b987ce372fae22dda35bd655b640b079a6fd#diff-0338d7b17cce00995fa6c4045a88a74a  lo volvistes a habilitar, pero ya busque ese metodo _check_and_recompute_days y no existe en ningun modulo, o lo tienes en otro modulo???

**Comment by nelsonramirezs** [comment]
Lo que quería hacer era recalcular los días cada vez que cambiara el tipo de ausencia, ya que las vacaciones solo debe tomar los días hábiles. Se puede quitar mientras tanto.

**Comment by nelsonramirezs** [comment]
Con el commit 2c87a5c se resuelve este tema.
