### ISSUE TITLE
Liquidaciones en 0 para mes por concluir

### ISSUE THREAD

**Issue by aristidescc** [KonosCL/addons-konos#30]
Hola! De antemano les agradezco y felicito por el trabajo con el módulo de Remuneraciones, me parece que funciona muy bien.

He seguido los videos de ejemplo, y de esa manera, al 25/09, he podido generar liquidaciones para el mes de Agosto (con indicadores de Septiembre), pero las liquidaciones de Septiembre (con indicadores de Octubre) me salen en 0. Los contratos son indefinidos, y no expiran en el mes.

Algo debo estar haciendo mal, y no logro detectar que puede ser. Alguna orientación al respecto? O es que las liquidaciones solo se pueden hacer a mes vencido? Digamos que las chicas de administración no están muy felices con esa idea.

Saludos!

**Comment by aristidescc** [comment]
Olvidé mencionar que estoy usando el módulo para Odoo V10

**Comment by nelsonramirezs** [comment]
Hola Aristides.
Revisa las fechas de la liquidación, fechas de los contratos. Elimina las liquidaciones y vuélvelas a emitir. 
Saludos,
