### ISSUE TITLE
Error tras instalar modulos

### ISSUE THREAD

**Issue by mattusaleen** [KonosCL/addons-konos#55]
Estimados.

Agradeceria la ayuda!

Despues de instalar el modulo account_payment_advance, odoo se fue a blanco, muestra solo una barra negra y el logo de la empresa, reviso el log y este error indica.

"POST /web/dataset/call HTTP/1.1" 200 -
"GET /web/?debug HTTP/1.1" 200 -

Me paso el mismo error con el modulo financial indicators 

Hasta ahora, lo unico que pude hacer fue iniciar nuevamente el VPS con una imagen de respaldo antes de instalar esos módulos.

Agradecería ayuda de que pudiera ser, he buscado por Internet y nada con el mismo error.

Saludos!

**Comment by dansanti** [comment]
Hola!, debes copiar el log inmediatamente después de reiniciar el servicio, porque si es poruna mala copia de archivos o porque falta una dependancia python,  sale ahí..

de todas formas esto debiera tratarse en un foro o por soporte, ya que no se explica de forma de desarrollo para este lugar
