### ISSUE TITLE
SEGURO CESANTIA

### ISSUE THREAD

**Issue by creichhardt** [KonosCL/addons-konos#59]
Hola,

No me calcula el SEGURO CESANTIA SECE en el modulo HR de la versión 12. Lo deja en 0 y cuando obtengo la liquidacion, me indica valor 0 en este ítem.

**Comment by creichhardt** [comment]
Otro error que aparece es: Al presionar Factura Rectificativa en Nominas. 
Código python erróneo en la regla de salario GRATIFICACION LEGAL (GRAT).

**Comment by nelsonramirezs** [comment]
Esto no es un error. 
SEGURO CESANTIA SECE: Asegúrate de que EL CONTRATO TENGA Plazo Indefinido. 
Factura Rectificativa no es compatible. Descarga el módulo de Payroll Cancel en Odoo apps. 
Saludos.
