### ISSUE TITLE
Falta AFP Nueva AFP Uno

### ISSUE THREAD

**Issue by Rafixed** [KonosCL/addons-konos#63]
Hola
Revisando el código me di cuenta que no está la nueva AFP Uno en el listado de AFP en [l10n_cl_hr](https://github.com/KonosCL/addons-konos/tree/11.0/l10n_cl_hr).
Esto puede causar más de algún dolor de cabeza al calcular remuneraciones de empleados afiliados a esta nueva afp.

Saludos!

R

**Comment by fc-azurtech** [comment]
Hola, 

buenas tardes, lograron agregar la nueva afp UNO?

**Comment by fc-azurtech** [comment]
Listo, ya lo agregue al código, donde puedo contruibuir con este granito de arena?

**Comment by celm1990** [comment]
> Listo, ya lo agregue al código, donde puedo contruibuir con este granito de arena?

Hola, haz un fork del repo, crea una rama y ahi sube los cambios, luego de eso crea un Pull Requests
