### ISSUE TITLE
Calculo de nomina Salud 

### ISSUE THREAD

**Issue by mattusaleen** [KonosCL/addons-konos#68]
Hola estimados, tengo un problema en el calculod e nomina en el item salud me calcula todo el plan como cotización adicional y el aporte obligatorio me lo deja en 0, sera una configuración o algo? 

gracias de antemano.

**Comment by nelsonramirezs** [comment]
Hola @mattusaleen, Asegúrate de tener configurada la pestaña de instituciones relaciones en Indicadores Previsionales. 

Tasa | 0,60
Fonasa | 6,40
Fondo de Pensiones | 18,84
Tope Imponible Salud % | 7,00
ISL | 0,93

Saludos!
